apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: catalognodejs-deployment
spec:
  selector:
    matchLabels:
      app: catalog
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: nginx
        image: catalognd:1.0
        ports:
        - containerPort: 3001